NPP_ANALYSIS_DIR = $(shell $(NPP)/bin/extract_parameter.sh $(CONFIG) npp_analysis_dir)
RUN = $(shell $(NPP)/bin/extract_parameter.sh $(CONFIG) run_number)
EVENTS = $(shell $(NPP)/bin/extract_parameter.sh $(CONFIG) number_of_events)
GEN_CFG_SIG = $(shell $(NPP)/bin/extract_parameter.sh $(CONFIG) generator_config_file_signal)
GEN_CFG_PS = $(shell $(NPP)/bin/extract_parameter.sh $(CONFIG) generator_config_file_phase_space)
MC_OUTPUT_DIR = $(shell $(NPP)/bin/extract_parameter.sh $(CONFIG) mc_output_dir)
BATCH = $(shell $(NPP)/bin/extract_parameter.sh $(CONFIG) batch 0)
BASE_FILE_NUMBER = $(shell $(NPP)/bin/extract_parameter.sh $(CONFIG) base_file_number 0)
GENERATOR = $(shell $(NPP)/bin/extract_parameter.sh $(CONFIG) generator_program gen_2pi0_primakoff)
GENERATOR_CONFIG_FILE = $(shell $(NPP)/bin/extract_parameter.sh $(CONFIG) generator_config_file gen_2pi0_primakoff)

